# pcplus backend api local run settings

spring.datasource.url=jdbc:postgresql://ep-raspy-fog-anhd61ex-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wQf4rpSFI7gk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

server.port=8081
pcplus.cors.allowed-origin=http://localhost:3000

pcplus.jwt.secret=PCPlusSecretKey_ChangeThisInProduction_CSC340_Group4_2026
pcplus.jwt.expiration-ms=86400000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.pcplus=DEBUG
logging.level.org.springframework.security=WARN